

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData V3                                    /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function(global, $data, undefined) {

  $data.Entity.extend('ChinookModel.Album', {
    'AlbumId': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
    'Title': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':160 },
    'ArtistId': { 'type':'Edm.Int32','nullable':false,'required':true },
    'Artist': { 'type':'ChinookModel.Artist','required':true,'inverseProperty':'Albums' },
    'Tracks': { 'type':'Array','elementType':'ChinookModel.Track','inverseProperty':'Album' }
  });
  
  $data.Entity.extend('ChinookModel.Artist', {
    'ArtistId': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
    'Name': { 'type':'Edm.String','maxLength':120 },
    'Albums': { 'type':'Array','elementType':'ChinookModel.Album','inverseProperty':'Artist' }
  });
  
  $data.Entity.extend('ChinookModel.Genre', {
    'GenreId': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
    'Name': { 'type':'Edm.String','maxLength':120 },
    'Tracks': { 'type':'Array','elementType':'ChinookModel.Track','inverseProperty':'Genre' }
  });
  
  $data.Entity.extend('ChinookModel.MediaType', {
    'MediaTypeId': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
    'Name': { 'type':'Edm.String','maxLength':120 },
    'Tracks': { 'type':'Array','elementType':'ChinookModel.Track','inverseProperty':'MediaType' }
  });
  
  $data.Entity.extend('ChinookModel.Playlist', {
    'PlaylistId': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
    'Name': { 'type':'Edm.String','maxLength':120 },
    'Tracks': { 'type':'Array','elementType':'ChinookModel.Track','inverseProperty':'Playlists' }
  });
  
  $data.Entity.extend('ChinookModel.Track', {
    'TrackId': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
    'Name': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':200 },
    'AlbumId': { 'type':'Edm.Int32' },
    'MediaTypeId': { 'type':'Edm.Int32','nullable':false,'required':true },
    'GenreId': { 'type':'Edm.Int32' },
    'Composer': { 'type':'Edm.String','maxLength':220 },
    'Milliseconds': { 'type':'Edm.Int32','nullable':false,'required':true },
    'Bytes': { 'type':'Edm.Int32' },
    'UnitPrice': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'Album': { 'type':'ChinookModel.Album','inverseProperty':'Tracks' },
    'Genre': { 'type':'ChinookModel.Genre','inverseProperty':'Tracks' },
    'MediaType': { 'type':'ChinookModel.MediaType','required':true,'inverseProperty':'Tracks' },
    'Playlists': { 'type':'Array','elementType':'ChinookModel.Playlist','inverseProperty':'Tracks' }
  });
  
  $data.EntityContext.extend('ChinookService.Models.ChinookEntities', {
    'Albums': { type: $data.EntitySet, elementType: ChinookModel.Album },
    'Artists': { type: $data.EntitySet, elementType: ChinookModel.Artist },
    'Genres': { type: $data.EntitySet, elementType: ChinookModel.Genre },
    'MediaTypes': { type: $data.EntitySet, elementType: ChinookModel.MediaType },
    'Playlists': { type: $data.EntitySet, elementType: ChinookModel.Playlist },
    'Tracks': { type: $data.EntitySet, elementType: ChinookModel.Track }
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(ChinookService.Models.ChinookEntities);
  
  /*Context Instance*/
  ChinookService.Models.context = new ChinookService.Models.ChinookEntities( { name:'oData', oDataServiceHost: 'http://localhost:1114/ChinookDataService.svc' });

      
})(window, $data);
      
    